//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.12 at 10:05:46 PM IST 
//


package com.dyasha.mywebapp.entity.google.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeocodeResponseXML }
     * 
     */
    public GeocodeResponseXML createGeocodeResponse() {
        return new GeocodeResponseXML();
    }

    /**
     * Create an instance of {@link GeocodeResponseXML.Result }
     * 
     */
    public GeocodeResponseXML.Result createGeocodeResponseResult() {
        return new GeocodeResponseXML.Result();
    }

    /**
     * Create an instance of {@link GeocodeResponseXML.Result.Geometry }
     * 
     */
    public GeocodeResponseXML.Result.Geometry createGeocodeResponseResultGeometry() {
        return new GeocodeResponseXML.Result.Geometry();
    }

    /**
     * Create an instance of {@link GeocodeResponseXML.Result.Geometry.Bounds }
     * 
     */
    public GeocodeResponseXML.Result.Geometry.Bounds createGeocodeResponseResultGeometryBounds() {
        return new GeocodeResponseXML.Result.Geometry.Bounds();
    }

    /**
     * Create an instance of {@link GeocodeResponseXML.Result.Geometry.Viewport }
     * 
     */
    public GeocodeResponseXML.Result.Geometry.Viewport createGeocodeResponseResultGeometryViewport() {
        return new GeocodeResponseXML.Result.Geometry.Viewport();
    }

    /**
     * Create an instance of {@link GeocodeResponseXML.Result.AddressComponent }
     * 
     */
    public GeocodeResponseXML.Result.AddressComponent createGeocodeResponseResultAddressComponent() {
        return new GeocodeResponseXML.Result.AddressComponent();
    }

    /**
     * Create an instance of {@link GeocodeResponseXML.Result.Geometry.Location }
     * 
     */
    public GeocodeResponseXML.Result.Geometry.Location createGeocodeResponseResultGeometryLocation() {
        return new GeocodeResponseXML.Result.Geometry.Location();
    }

    /**
     * Create an instance of {@link GeocodeResponseXML.Result.Geometry.Bounds.Southwest }
     * 
     */
    public GeocodeResponseXML.Result.Geometry.Bounds.Southwest createGeocodeResponseResultGeometryBoundsSouthwest() {
        return new GeocodeResponseXML.Result.Geometry.Bounds.Southwest();
    }

    /**
     * Create an instance of {@link GeocodeResponseXML.Result.Geometry.Bounds.Northeast }
     * 
     */
    public GeocodeResponseXML.Result.Geometry.Bounds.Northeast createGeocodeResponseResultGeometryBoundsNortheast() {
        return new GeocodeResponseXML.Result.Geometry.Bounds.Northeast();
    }

    /**
     * Create an instance of {@link GeocodeResponseXML.Result.Geometry.Viewport.Southwest }
     * 
     */
    public GeocodeResponseXML.Result.Geometry.Viewport.Southwest createGeocodeResponseResultGeometryViewportSouthwest() {
        return new GeocodeResponseXML.Result.Geometry.Viewport.Southwest();
    }

    /**
     * Create an instance of {@link GeocodeResponseXML.Result.Geometry.Viewport.Northeast }
     * 
     */
    public GeocodeResponseXML.Result.Geometry.Viewport.Northeast createGeocodeResponseResultGeometryViewportNortheast() {
        return new GeocodeResponseXML.Result.Geometry.Viewport.Northeast();
    }

}
