//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.11 at 12:04:50 PM IST 
//


package com.dyasha.mywebapp.entity.weather.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dyasha.mywebapp.entity.weather package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dyasha.mywebapp.entity.weather
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WeatherDetailsXML }
     * 
     */
    public WeatherDetailsXML createCurrent() {
        return new WeatherDetailsXML();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.Wind }
     * 
     */
    public WeatherDetailsXML.Wind createCurrentWind() {
        return new WeatherDetailsXML.Wind();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.City }
     * 
     */
    public WeatherDetailsXML.City createCurrentCity() {
        return new WeatherDetailsXML.City();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.Temperature }
     * 
     */
    public WeatherDetailsXML.Temperature createCurrentTemperature() {
        return new WeatherDetailsXML.Temperature();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.Humidity }
     * 
     */
    public WeatherDetailsXML.Humidity createCurrentHumidity() {
        return new WeatherDetailsXML.Humidity();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.Pressure }
     * 
     */
    public WeatherDetailsXML.Pressure createCurrentPressure() {
        return new WeatherDetailsXML.Pressure();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.Clouds }
     * 
     */
    public WeatherDetailsXML.Clouds createCurrentClouds() {
        return new WeatherDetailsXML.Clouds();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.Precipitation }
     * 
     */
    public WeatherDetailsXML.Precipitation createCurrentPrecipitation() {
        return new WeatherDetailsXML.Precipitation();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.Weather }
     * 
     */
    public WeatherDetailsXML.Weather createCurrentWeather() {
        return new WeatherDetailsXML.Weather();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.Lastupdate }
     * 
     */
    public WeatherDetailsXML.Lastupdate createCurrentLastupdate() {
        return new WeatherDetailsXML.Lastupdate();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.Wind.Speed }
     * 
     */
    public WeatherDetailsXML.Wind.Speed createCurrentWindSpeed() {
        return new WeatherDetailsXML.Wind.Speed();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.Wind.Direction }
     * 
     */
    public WeatherDetailsXML.Wind.Direction createCurrentWindDirection() {
        return new WeatherDetailsXML.Wind.Direction();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.City.Coord }
     * 
     */
    public WeatherDetailsXML.City.Coord createCurrentCityCoord() {
        return new WeatherDetailsXML.City.Coord();
    }

    /**
     * Create an instance of {@link WeatherDetailsXML.City.Sun }
     * 
     */
    public WeatherDetailsXML.City.Sun createCurrentCitySun() {
        return new WeatherDetailsXML.City.Sun();
    }

}
